= Block Message Workflow
Peter Lawrey

Messages are passed around the platform to package up transactions into block, vote on the order of those blocks, and choose and order.

=== Inbound messages

Commands and Events are passed to the block chain after being validated by the Fast Path component.

Queries and responses are never passed to the block chain. They are only exchanged between a requesting client and a server.

NOTE: Servers act as client to other servers blurring the distinction. For the purpose of the discussion, the client queries and the server responds

Time is divided into rounds of equal length. e.g. 10 milli-seconds. At the end of each round new blocks are added to the end of the tree determining the order all servers should process the blocks.

This component takes all message types.

=== Fast Path component

The Fast path component validates commands and in some cases handles the command itself directly.
Initially this will be very few commands, however the aim is to handle as much as 95% of commands in the fast path,
avoiding the need to wait for the block chain.

Once a command has been validated, a command is passed to the block chain. The command might be different if the Fast path handles it, or the same if not.

This component takes all message types.

=== Chainer

The Chainer takes Commands from the Fast Path and Events from the Post Block Chain processor and adds them to a Transaction Block.

This block is a chained from the last block the same server produced. It is after;

- every other block this server produced.
- every block already added to a Tree.

However, it's order relative to new blocks produced by other servers needs to be determined in the voting phase

This component takes all message types and produces blocks

=== Voting component

The voting component looks at all the new blocks it has produced or have been replicated to it and proposes a new tree node.

The blocks in this proposed extension to the tree, come after all the blocks already in the tree, and in eventTime chronological order within this proposal.

NOTE: it is possible and likely some blocks will be out of order by time between rounds of voting.

This component only processes Transaction Blocks and produces a vote message.

=== VoteTaker component

The vote taker listens to votes in a given round. Once a majority of servers vote on the same proposal a new tree node is created. The round is abandoned if

- a majority cannot be reached.
- a majority is reached on a later round.

This component only processes the vote messages and produces a TreeNode

=== BlockReplayer component

The Block Replayer, replays the events in order to the Post BlockChain component which determines the Commands outcomes.

This component processes Blocks and TreeNodes and produces all the messages in the blocks.

=== PostBlockChainProcessor component

This component processes the messages and can issue any message.

=== FinalMessageRouter component

This component takes messages and passes them to the gateway, or another server, or passes them to the Chainer.
