= XCL Block Chain
Peter Lawrey

The XCL Block Chain is an ordered collection of messages as commands + events and queries + responses. Its structure contains:

- Signed Messages.
- A Transaction Block which is a list of messages produced by a single node.
- A End of Round Block which describes the order of these blocks.

All data is in little endian. All strings use UTF-8 encoding.

NOTE: Events must come from a trusted source.
i.e. a recognised node in the current cluster, or a recognised node in the previous week's cluster.


== Message types

Message types are defined in the https://github.com/OpenHFT/Chronicle-Accelerate/blob/master/api/src/main/java/cash/xcl/api/dto/MethodIds.java[MethodIds] class.

=== Trailing zeros

All messages have notionally endless zeros at the end.
If the schema changes and a field is added, it should be filled with 0 bytes; i.e. false, empty string, 0, or 0.0 as appropriate.
If the message sent has more bytes than expected, they may be silently ignored.

NOTE: The signature will always include only the bytes actually written and not include the notional extra zero bytes.

=== Signed Messages

Messages written are either commands (an instruction to take an action which might be rejected), or events (something which has happened, might not need an action but cannot be rejected).

The message format looks like:

[width="80%",cols="1,3",options="header"]
|===
| Byte offset | Field
| 0 - 63 | Signature
| 64 - 71 | Source address
| 72 - 79 | Event timestamp
| 80 - 80 | Protocol version == 1 (1.)
| 81 - 81 | Message type (for version)
| 82 - 83 | Week number
| 84 - 87 | Block in week for source
| 84+ | The rest of the message depending on the message type
|===
<1> In the future, two protocol versions might be supported while an old one is deprecated.

=== Transaction Block Event (message type = 0x01)

The transaction block is a signed message which contains zero or more messages.

[width="80%",cols="1,3",options="header"]
|===
| Byte offset | Field
| 0 - 81 | Message header
| 82 - 83 | Week number
| 84 - 87 | Block in week for source (1.)
| 88 - 89 | The first message length
| 90+ | The first message
| Later | Additional messages
|===
<1> Allows for 4 billion blocks per week, per source.

Within the transaction block, each message is preceded by a message length which is 2 byte unsigned length.

=== Transaction Block Gossip Event (message type = 0x02)

The message publishes which blocks this node has received.

=== Transaction Block Vote Event (message type = 0x03)

The message publishes a vote on what the next End of Round Block Event should be.

=== End Of Round Block Event (message type = 0x04)

The transaction block is a signed message which contains zero or more messages.

[width="80%",cols="1,3",options="header"]
|===
| Byte offset | Field
| 0 - 81 | Message header
| 82 - 83 | Week number
| 84 - 87 | Block in week for source
| 88 - 95 | The first source address
| 96 - 99 | The first block number
| 100 - 103 | The first block status (1.)
| 104+ | Any additional block entries
|===
<1> The block status records how many times it has been replicated and whether it was timed out or not.

=== Opening Balance Event (0x05)

This event holds the opening balance for an address at the start of the week.
It is also the event produced at the end of the week to record the balance.

This message: 

 - is an event to set the initial state of an address.
 - is dumped as part of the snap shot at the end of each week and loaded at the start of the next week.
 - must come from a trusted source or it will be rejected.

The message contains:

- the list of currencies and balances

=== Fees Event (0x06)

This event records the fee structure determined by the AI at the start of the week.

=== Exchange Rates Event (0x07)

This event lists all the weekly exchange rates with mid price. It is used to calculate fees when the balance is in other currencies.

=== Service Nodes Event (0x08)

This event lists all the nodes in a cluster for a service.

=== Block Subscription Query (0x0f)

Requests a block be sent from a given block number in a week, for that node.

Note: If the requested block number is -1, all the check point blocks (Weekly Events written) from the previous week will also be sent.

== Runtime Events

These events can occur at any time and on any chain.

=== Application Message Event (0x10)

This event records that something went wrong, most likely unable to be handled automatically.

When an event fails to be processed, it could trigger one of these events.

=== Command Failed Message Event (0x11)

This event records that an error occured processing a command in a way which might be processed automatically.

When a command fails to be processed it could trigger one of these events.

=== Query Failed Response (0x12)

This response occurs when there is an error in processing a query in a way which might be processed automatically.

When a query fails to be processed it could trigger one of these events.

NOTE: Responses are not written to a chain, only the connection sending the query.

== Main Chain Command/Queries

Main Chain Commands are commands which are used to execute Global operations; i.e. operations which apply to all regions in the world. The results of executing these commands are new transactions being executed and then persisted to the Main Blockchain. The Main Blockchain holds cross-regional data like ...

* Create New Address Command (0x20)
* Cluster Transfer Value Step1 Command (0x21)
* Cluster Transfer Value Step2 Command (0x22)
* Cluster Transfer Value Step3 Command (0x23)

Range 0x20 - 0x2f

=== Create New Address Command (0x20)

This message is a command to request that a new account be created. This includes the public key and the region in which to create the address:

[width="50%",options="header"]
|===
| Success | Error
| Address Information Event (0x30) | Command Failed Event (0x11)
|===

=== Cluster Transfer Value Step1 Command (0x21)

This message is a command to transfer value from one cluster to another, via the main chain.

The first step is to approve money be taken out of an account in one region/cluster.

[width="50%",options="header"]
|===
| Success | Error
| Cluster Transfer Value Step2 Command (0x22) | Command Failed Event (0x11)
|===

=== Cluster Transfer Value Step2 Command (0x22)

This message is a command to transfer value from one cluster to another, via the main chain.

The second step is to pass the transfer main chain can reject it if a node or cluster fails risk checks; e.g. transfers too much money, too quickly.

[width="50%",options="header"]
|===
| Success | Error
| Cluster Transfer Value Step3 Command (0x23) | Command Failed Event (0x11)
|===

=== Cluster Transfer Value Step3 Command (0x23)

This message is a command to transfer value from one cluster to another via the main chain.

The last step is to notify the target cluster to add to the balance of an address.

[width="50%",options="header"]
|===
| Success | Error
| Cluster Transfer Value Step3 Event (0x33) | Application Message Event (0x10)
|===

=== Clusters Status Query (0x2f)

This message is a query for all the known clusters and the services they provide.

[width="50%",options="header"]
|===
| Success | Error
| Cluster Transfer Value Event (0x31) | Query Failed Response (0x12)
|===

== Main Chain Events

Main Chain Events are events which are sent as a result of executing Main Chain Commands. These events are confirmation of transactions performed at the global level; i.e. transactions which apply to all regions in the world. These events are published after the transactions have been executed, confirmed and persisted to the Main Blockchain.


Range 0x30 - 0x3f

=== Create New Address Event (0x30)

This message:

 - is an event from the main chain to set the reference information of an address.
 - is dumped as part of the snap shot at the end of each week and loaded at the start of the next week.
 - must come from the main chain or it will be rejected.

The message includes:

- the public key of the address.
- the list of verifiable facts about the account.

// todo add table showing example of success and error if needed

=== Cluster Transfer Step3 Event (0x33)

Value was successfully added to an address after transferring it from another cluster.

// todo add table showing example of success and error if needed

=== Clusters Status Response (0x3f)

A message detailing all the known clusters, their services and their host connection details.

// todo add table showing example of success and error if needed

== Regional Chain Commands

Regional Chain Commands are commands that are relevant to a specific region, as opposed to Main Chain Commands that apply globally to all regions across the world.

The results of these commands are persisted to the Regional Blockchain for the appropriate region.


// todo add table showing example of success and error if needed

Range 0x40 - 0x4f

=== Transfer Value Command (0x40)

This message is a command to transfer value from one address to another in the same chain.

The first step is to approve money be taken out of an account in one region/cluster.

[width="50%",options="header"]
|===
| Success | Error
| Transfer Value Event (0x50) | Command Failed Event (0x11)
|===

=== Subscription Query (0x4c)

// todo add descripton of what this messages means

[width="50%",options="header"]
|===
| Success | Error
| Subscription Success Response (0x5c) | Query Failed Response (0x12)
|===

=== Current Balance Query (0x4d)

The Current Balance Query message is a query for the current balance of an account address. An account address has a number of balances, one for each currency or asset held in the account. This message is a request for all balances for all currencies held within a given account.

[width="50%",options="header"]
|===
| Success | Error
| Current Balance Response (0x5d) | Query Failed Response (0x12)
|===

=== Exchange Rate Query (0x4e)

This message is a query for the latest Mid rate between 2 currencies, for example, the XCL/USD exchange rate.

The Mid rates are calculated by the appropriate Exchange service for that currency/asset pair. 
For example, the XCL/USD exchange rate will be calculated by the XCL/USD Exchange service. This service will return the Mid rate for 1,000,000 USD (?)

[width="50%",options="header"]
|===
| Success | Error
| Exchange Rate Response (0x5e) | Query Failed Response (0x12)
|===

=== Cluster Status Query (0x4f)

The Cluster Status Query message is a query for the status of the nodes in the current cluster. A node can have one of these status:

    * WAITING_FOR_APPROVAL
    * APPROVED_AND_NEVER_RUN
    * RUNNING
    * RUNNING_AND_DOING_ROUND_PROCESSING
    * NOT_RUNNING
    * DISABLED

[width="50%",options="header"]
|===
| Success | Error
| Cluster Status Response (0x5f) | Query Failed Response (0x12)
|===

== Regional Chain Events

Regional Chain Events are events which are published in response to Regional Chain Commands.

These are the Regional Chain Events:

* Transfer Value Event (0x50)
// todo any more events?

Range 0x50 - 0x5f

NOTE: Events and Responses are always assumed to be successfully processed or ignored unless an Application Message Event (0x10) is produced.

=== Transfer Value Event (0x50)

The Transfer Value Event message is an event which is sent in response to a `Transfer Value Command`
message.

This event message contains the details of the transfer:

* sender's account address
* receiver's account address
* amount transferred
* currency
* timestamp

== Regional Chain Responses

Regional Chain Responses are commands which are sent in response to Regional Chain Queries.
These response messages are:

* Subscription Success Response (0x5c)
* Current Balance Response (0x5d)
* Cluster Status Response (0x5f)
* Clusters Status Response (0x3f)
* Exchange Rate Response (0x5e)

=== Subscription Success Response (0x5c)

The Subscription Success Response message is a message which is sent in response to a
`Subscription Command` message.

=== Current Balance Response (0x5d)

The Current Balance Response message is the message sent in response to the `Current Balance Query (0x4d)` message.

This message will contain, for a given account address, the list of currencies/assets and the current balance for each of them. For example:  

.Accelerate Account Address:   @gb1ndar3bfw93
[width="50%",options="header"]
|====================
| Currency  | Amount
| XCL  |     2,434
| GBP  | 3,493,343
| USD  |    34,893
|====================

=== Exchange Rate Response (0x5e)

The Exchange Rate Response message is sent in response to the `Exchange Rate Query (0x4e)` message.

This message will contain the latest exchange Mid rates between 2 assets; e.g. currencies, crypto currencies, etc. 

For example, a standard response will look something like:

[width="50%",options="header"]
|====================
| Currencies  |  mid | spread
| USD/XCL  |  2.3493 | 0.0011
|====================

The Mid rates are calculated by the appropriate Exchange service for that currency/asset pair. For example, the XCL/USD exchange rate will be calculated by the XCL/USD Exchange service. This service will return the Mid rate for 1 million USD 
// todo USD?


=== Cluster Status Response (0x5f)

The Cluster Status Response message is the message sent in response to the `Cluster Status Query (0x4f)` message.

This message contains the status of all the nodes in the current cluster. A node can have one of these status:

    * WAITING_FOR_APPROVAL
    * APPROVED_AND_NEVER_RUN
    * RUNNING
    * RUNNING_AND_DOING_ROUND_PROCESSING
    * NOT_RUNNING
    * DISABLED


== Service Chain Commands

Service Chain Commands are commands which are used to perform service type operations like:

* depositing and withdrawing funds.
* placing Market/Limit orders in the Accelerate market.

These commands are:

* Deposit Value Command (0x60)
* Withdraw Value Command (0x61)
* Market Order to Buy/Sell XCL (0x62)
* Limit Order to Buy/Sell XCL (0x63)
* Cancel Order to Buy/Sell XCL (0x64)

These commands are typically issued by a user from the Accelerate Website page.

Service Chain Commands are requests to perform transactions which are persisted to the appropriate regional blockchain; i.e the blockchain for that region.


Range 0x60 - 0x6f

=== Deposit Value Command (0x60)

This message is a command to make a deposit for an amount of standard real currenc, e.g. Sterling Pounds or Dollars, into an Accelerate address account. 

A user would typically make this deposit on the Accelerate Website page by making a standard Debit/Credit card payment into their personal Accelerate account address.

[width="50%",options="header"]
|===
| Success | Error
| Deposit Value Event (0x70) | Command Failed Event (0x11)
|===

=== Withdraw Value Command (0x61)

The Withdraw Value Command message is a command to make a withdrawal from an Accelerate account address and deposit the funds into a user's personal retail bank account.

A user would typically issue this withdrawal on the Accelerate Website page by requesting a standard bank transfer from their Accelerate account address to their personal retail bank account.

If the user is withdrawing funds held in XCL, then this withdrawal will involve a currency conversion from XCL to the user's home currency; e.g. Sterling Pounds or US Dollars.


[width="50%",options="header"]
|===
| Success | Error
| Withdraw Value Event (0x71) | Command Failed Event (0x11)
|===

=== Market Order to Buy/Sell XCL (0x62)

The Market Order Command message is a command which is used to place a Market Order to buy or sell an amount of XCL on the Accelerate market at the current live market price.

A Market Order is a type of Order that executes immediately at the best available price in the market.

A user would typically place their Market Order on the Accelerate Website page.

The result of placing a Market Order is a `Execution Report (0x72)` which will be executed immediately after the market order is placed at the best available price at the time.

[width="50%",options="header"]
|===
| Success | Error
| Execution Report (0x72) | Command Failed Event (0x11)
|===


=== Limit Order to Buy/Sell XCL (0x63)

The Limit Order Command message is a command which is used to place a Limit Order to buy or sell an amount of XCL on the Accelerate market at a specified price.

A Limit Order is a type of order to execute a trade at a given maximum price, if buying, or at a given minimum price, if selling. This given price is called the Limit Price.

A Limit Order may never be executed, but it guarantees that if it is executed, it will be at the specified limit price or better.

A user would typically place their Limit Order on the Accelerate Website page.

After placing a Limit Order, a trade might be executed immediately or at some point in the future or not at all, depending on how aggressive the specified Limit Price is and the currently available live prices in the market.

The result of placing a Limit Order is a `Execution Report Event (0x72)` but only, if and when, a trade takes place at the requested Limit Price.

[width="50%",options="header"]
|===
| Success | Error
| Execution Report (0x72) | Command Failed Event (0x11)
|===

=== Cancel Order to Buy/Sell XCL (0x64)

The Cancel Order Command message is a command to cancel a Market or Limit Order that a user previously placed in the Accelerate market.

[width="50%",options="header"]
|===
| Success | Error
| Execution Report (0x72) | Command Failed Event (0x11)
|===

== Service Chain Events

Service Chain Events are events which are sent confirming that a Service Chain Command was executed successfully.
Service Chain Events contain the details of the transaction that was executed.

These events are:

* Deposit Value Event (0x70)
* Withdraw Value Event (0x71)
* Execution Report to Buy/Sell XCL (0x72)

Range 0x70 - 0x7f

NOTE: Events and Responses are always assumed to be successfully processed or ignored unless an Application Message Event (0x10) is produced.

=== Deposit Value Event (0x70)

A Deposit Value Event message is a message which is sent as a response to a `Deposit Value Command` message.

The Deposit Value Event message contains confirmation of all the deposit details including:

* the amount deposited 
* the currency
* the user's account address


// todo add table showing example of success and error

=== Withdraw Value Event (0x71)

A Withdraw Value Event is an event which is sent as a response to a `Withdraw Value Command` message.

The Withdraw Value Event contains confirmation of the withdrawal details including:

* the amount withdrawn
* the currency
* the user's account address


=== Execution Report Event (0x72)

An Execution Report message is a message which is sent as a confirmation message of a trade executed in the Accelerate market. The Execution Report Event message contains:

* the amount bought or sold
* the currency pair
* the price of the trade

Execution Reports are sent as a result of placing a Market or Limit Order on the Accelerate market.

// THE END
