= Chronicle-Accelerate
Peter Lawrey, Sabrina Rai
 


== Chronicle-Accelerate (XCL)

XCL is a new cryptocurrency project that, learning from the previous Blockchain implementations, aims to solve the issues limiting adoption by building an entirely new protocol that can scale to millions of transactions per second, delivering consistent  sub-second latency. Our platform will leverage AI to control volatility and liquidity, require low energy and simplify compliance with integrated KYC and AML support.

The XCL platform combines low latencies (sub millisecond), IoT transaction rates (millions/s), open source AI volatility controls and blockchain for transfer of value and exchange of value for virtual fiat and crypto currencies. This system could be extended to other asset classes such as securities and fixed income. It uses a federated services model and regionalized payment systems making it more scalable than a blockchain which requires global consensus.

The platform makes use of https://github.com/OpenHFT/Chronicle-Salt/blob/master/README.adoc[Chronicle-Salt] for encryption and https://github.com/OpenHFT/Chronicle-Bytes[Chronicle-Bytes] add description -what is chronicle-bytes for?


== Message Types

https://github.com/OpenHFT/Chronicle-Accelerate/blob/master/rfc/XCLBlockChain.adoc[Details on how the messages are used]
