package cash.xcl.api.dto;

public interface MethodIds {
    int TRANSACTION_BLOCK_EVENT = 0x01;
    int TREE_BLOCK_EVENT = 0x02;
    int APPLICATION_MESSAGE_EVENT = 0x03;

    int CREATE_NEW_ADDRESS_COMMAND = 0x20;
    int NEW_ADDRESS_REJECTED_EVENT = 0x21;
    int ADDRESS_INFORMATION_EVENT = 0x22;

    int CLUSTER_TRANSFER_VALUE_COMMAND = 0x30;
    int CLUSTER_TRANSFER_VALUE_REJECTED_EVENT = 0x31;
    int CLUSTER_TRANSFER_INFORMATION_EVENT = 0x32;

    int EXCHANGE_RATE_EVENT = 0x33;
    int OPENING_BALANCE_EVENT = 0x34;

    int TRANSFER_VALUE_COMMAND = 0x50;
    int TRANSFER_VALUE_REJECTED_EVENT = 0x51;
    int TRANSFER_VALUE_INFORMATION_EVENT = 0x52;

    int DEPOSIT_VALUE_COMMAND = 0x60;
    int DEPOSIT_VALUE_REJECTED_EVENT = 0x61;
    int DEPOSIT_INFORMATION_EVENT = 0x62;

    int WITHDRAW_VALUE_COMMAND = 0x63;
    int WITHDRAW_VALUE_REJECTED_EVENT = 0x64;
    int WITHDRAW_VALUE_INFORMATION_EVENT = 0x65;

    int NEW_MARKET_ORDER = 0x66;
    int NEW_LIMIT_ORDER = 0x67;
    int CANCEL_ORDER = 0x68;
    int EXECUTION_REPORT = 0x70;

    int SUBSCRIPTION_COMMAND = 0xF0;
    int SUBSCRIPTION_SUCCESS_EVENT = 0xF1;
    int SUBSCRIPTION_FAILED_EVENT = 0xF2;

    int FEES_EVENT = 0xF3;
}
