package cash.xcl.api.dto;

public interface MethodIds {
    int TRANSACTION_BLOCK_EVENT = 0x01;
    int TREE_BLOCK_EVENT = 0x02;
    int CREATE_NEW_ADDRESS_COMMAND = 0x20;
    int CLUSTER_TRANSFER_VALUE_COMMAND = 0x21;
    int ADDRESS_INFORMATION_EVENT = 0x30;
    int EXCHANGE_RATE_EVENT = 0x31;
    int NEW_ADDRESS_REJECTED_EVENT = 0x32;
    int OPENING_BALANCE_EVENT = 0x50;
    int TRANSFER_VALUE_COMMAND = 0x51;
    int DEPOSIT_VALUE_COMMAND = 0x60;
    int WITHDRAW_VALUE_COMMAND = 0x61;
    int NEW_MARKET_ORDER = 0x62;
    int NEW_LIMIT_ORDER = 0x63;
    int CANCEL_ORDER = 0x64;
    int EXECUTION_REPORT = 0x70;

    int SUBSCRIPTION_COMMAND = 0xF0;
}
